{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_3():\n>       assert False\nE       assert False\n\ntest_parallel.py:12: AssertionError"}, "start": 1724030292214, "stop": 1724030292215, "uuid": "c2dbae06-8e4b-4ff8-8314-85ba6090c6b6", "historyId": "e3a9d1b5d4e93f911308a5e710828915", "testCaseId": "e3a9d1b5d4e93f911308a5e710828915", "fullName": "test_parallel#test_3", "labels": [{"name": "suite", "value": "test_parallel"}, {"name": "host", "value": "Abhishek"}, {"name": "thread", "value": "1804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_parallel"}]}