{"name": "test_5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_5():\n>       assert False\nE       assert False\n\ntest_parallel.py:18: AssertionError"}, "start": 1724030292318, "stop": 1724030292318, "uuid": "e1d47bf8-939e-43c3-b44b-b4358ac3014b", "historyId": "de23441aa86d93781c0ddb5a98a27f9b", "testCaseId": "de23441aa86d93781c0ddb5a98a27f9b", "fullName": "test_parallel#test_5", "labels": [{"name": "suite", "value": "test_parallel"}, {"name": "host", "value": "Abhishek"}, {"name": "thread", "value": "1804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_parallel"}]}